---
quasselcore:
  image: rtzq0/docker-quasselcore
  environment:
    - COUNTRY=US
    - STATE=California
    - CITY=Los Angeles
  hostname: localhost
  ports:
    - 4242:4242
  volumes:
    - /srv/docker/quasselcore:/var/lib/quassel
  restart: unless-stopped
