---

quasselcore:
  image: rtzq0/docker-quasselcore
  environment:
  - COUNTRY=US
  - STATE=California
  - CITY=Los Angeles
  hostname: quasselcore
  domainname: quasselcore.localdomain
  ports:
  - 4242:4242
  volumes:
  - /srv/docker/quasselcore:/var/lib/quassel
  restart: unless-stopped

quasselweb:
  image: rtzq0/docker-quasselweb
  environment:
  - COUNTRY=US
  - STATE=California
  - CITY=Los Angeles
  hostname: quasselweb
  domainname: quasselweb.localdomain
  ports:
  - 64443:64443
  volumes:
  - /srv/docker/quasselweb:/home/quasselweb/persist
  restart: unless-stopped
